config/routes.rb
Rails.application.routes.draw do
	# The root application route
  root 'welcome#index'

  controller :welcome do
	  get :home
	  get :about
	  get :contact
	end
  
  # vendors and products routes
  resources :vendors
  resources :products




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
end

app/controllers/vendor_controller.rb
class VendorController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	
  def index

  end

  def about

  end

  def contact
  	
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

def copyright_notice_year_range(start_year)
  # In case the input was not a number (nil.to_i will return a 0)
  start_year = start_year.to_i
  # Get the current year from the system
  current_year = Time.new.year
  
  if current_year > start_year && start_year > 2000
  	"#{start_year} - #{current_year}"
  elsif start_year > 2000
  	"#{start_year}"
  else
  	"#{current_year}"
  end
end

# Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Arusifiti For the Perfect wedding"
    if page_title.empty?
      base_title
    else
      page_title + " &bull; ".html_safe + base_title
    end
  end

end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/vendor_helper.rb
module VendorHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<div class="container">
		<div class="row">
			<div class="col-md-4 ft-link">
				<h2> ARUSIFITI </h2>
				<ul>
					<li><%= link_to "About", about_path %></li>
					<li><%= link_to "Blog", '#' %></li>
					<li><%= link_to "Price", '#' %></li>
					<li><%= link_to "Arusifiti Enterprise", '#' %></li>
				</ul>
			</div>
			<div class="col-md-4 ft-link">
				<h2> COMMUNITY </h2>
				<ul>
					<li><%= link_to "Press", '#' %></li>
					<li><%= link_to "Career", '#' %></li>
					<li><%= link_to "Vendor Review", '#' %></li>
					<li><%= link_to "Arusifiti Margazine ", '#' %></li>
				</ul>
			</div> 

			<div class="col-md-4 ft-link">
				<h2> HELP </h2>
				<ul>
					<li><%= link_to "Contact", contact_path %></li>
					<li><%= link_to "Support", '#' %></li>
					<li><%= link_to "Privacy Policy", '#' %></li>
					<li><%= link_to "Terms and Conditions", '#' %></li>
				</ul>
			</div>
		</div>

		<div class="social-icon"><!-- social icon -->
			<h2>We are Social </h2>
			<ul>
				<li><%= link_to ("http://facebook.com/arusifiti") do %> <i class='fa fa-facebook-square'> </i> <% end %></li>
				<li><%= link_to ("http://twitter.com/arusifiti") do %> <i class='fa fa-twitter-square'> </i> <% end %></li>
				<li><%= link_to ("http://instagram.com/arusifiti") do %> <i class='fa fa-instagram'> </i> <% end %></li>
				
			</ul>
		</div>
	</div>
</div>
<!-- /.Footer -->

<!-- Tiny footer -->
<div class="tiny-footer">
	<div class="container">
		<div class="row">

			<div class="col-md-12"> 
			&copy; <%= copyright_notice_year_range(2013) %> <%= link_to "Arusifiti Inc.", root_path %>  All Rights Reserved.</div>
		</div>
	</div>
</div>

app/views/layouts/_header.html.erb
<!-- Tob bar infor and links -->

<div class="top-bar">
	<div class="container">
		<div class="row">
			<div class="col-md-6 top-message"><p>Welcome to Arusifiti | For the Perfect Wedding</p></div>
			<div class="col-md-6 top-links">
				<ul class="listnone">
					<li><%= link_to("Are you a Couple?", '#' ) %></li>
					<li><%= link_to("Are you a vendor?", '#' ) %></li>
					<li><%= link_to("Log in", '#' ) %></li>
				</ul>
			</div>
		</div>    
	</div>
</div>
 
<!-- navigation start -->


<div class="tp-nav" id="headersticky">
	<div class="container">
		<nav class="navbar navbar-default "> 

			<!-- Brand and toggle get grouped for better mobile display -->

			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
					<span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
					<%=link_to("", root_path, :class => "navbar-brand img-responsive" ) %>
			</div>

			<!-- END Brand and toggle get grouped for better mobile display  -->

				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav navbar-right">

						<li class="dropdown"><%= link_to '#', class: "dropdown-toggle", 'data-toggle': 'dropdown' do %> Vendors <span class="fa fa-angle-down"></span> <% end %>
							
							<ul class="dropdown-menu">
								<li><%= link_to("Venue", '#' ) %></li>
								<li><%= link_to("Cake", '#' ) %></li>
								<li><%= link_to("Dresses", '#' ) %></li>
								<li><%= link_to("Photographer", '#' ) %></li>
								<li><%= link_to("Videography", '#' ) %></li>
								<li class="divide"></li>
								<li class="small"><%= link_to("See more &rarr;".html_safe , '#') %></li> 
							</ul>

						</li>
						<li class="dropdown"><%= link_to '#', class: "dropdown-toggle", 'data-toggle': 'dropdown' do %> Wedding Atire <span class="fa fa-angle-down"></span> <% end %>
							
							<ul class="dropdown-menu">
								<li><%= link_to("Dresses", '#' ) %></li>
								<li><%= link_to("Bridal Wear", '#' ) %></li>
								<li><%= link_to("Men wear", '#' ) %></li>
							</ul>

						</li>

						<li><%= link_to("Shop", ) %></li> 

						<li class="dropdown"><%= link_to '#', class: "dropdown-toggle", 'data-toggle': 'dropdown' do %> On-board <span class="fa fa-angle-down"></span> <% end %>
							
							<ul class="dropdown-menu">
								<li><%= link_to("Destinations", '#' ) %></li>
								<li><%= link_to("Honeymoon", '#' ) %></li>
								<li><%= link_to("Holiday", '#' ) %></li>
							</ul>
						</li>
						<li class="dropdown"><%= link_to '#', class: "dropdown-toggle", 'data-toggle': 'dropdown' do %> Planning <span class="fa fa-angle-down"></span> <% end %>
							
							<ul class="dropdown-menu">
								<li><%= link_to("Budget", '#' ) %></li>
								<li><%= link_to("Check List", '#' ) %></li>
							</ul>

						</li>
						<li class="dropdown"><%= link_to '#', class: "dropdown-toggle", 'data-toggle': 'dropdown' do %> Registry <span class="fa fa-angle-down"></span> <% end %>
							
							<ul class="dropdown-menu">
								<li><%= link_to("Save-the-date", '#' ) %></li>
								<li><%= link_to("Engagement", '#' ) %></li>
								<li><%= link_to("Wedding Website", '#' ) %></li>
							</ul>

						</li>
					</ul>
				</div>      
				<!-- /.navbar-collapse --> 

			</nav>
		</div>
		<!-- /.container-fluid --> 
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title><%= full_title(yield(:title)) %></title>

	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag 'application', media: 'all','data-turbolinks-track': 'true' %>
	
	
	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  	<!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
	<%= favicon_link_tag 'favicon.ico', rel: 'shortcut icon', type: 'image/x-icon' %>

</head>
<body>
	<!-- header -->
	<%= render 'layouts/header' %>

	<%= yield %>

	<!-- Footer -->
	<%= render 'layouts/footer' %>

	<!-- /. Tiny Footer -->
	<%= javascript_include_tag "application" %>
<!-- 	<%= yield :js %> -->
</body>
</html>

app/views/welcome/about.html.erb
<%provide(:title, "About") %>

<!-- page header -->
<div class="tp-page-head">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="page-header">
					<h1> About Arusifiti </h1>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- /.page header -->
<div class="main-container">
	<div class="container">
		<div class="row">
			<div class="col-md-3 side-nav" id="leftCol">
				<div class="hide-side">
					<ul class="listnone nav" id="sidebar">
						<li class="active"><%= link_to "About us", '#aboutus' %></li>
						<li><%= link_to "Meet The Team", '#team' %></li>
						<li><%= link_to "How it works", '#howwork' %></li>
						<li><%= link_to "Our History", '#history' %></li>
					</ul>
				</div>
			</div>
			<div class="col-md-9 content-right">
				<div class="row">
					<div class="call-to-action well-box" id="aboutus">
							<h1> For the perfect wedding </h1>
							<h3 class="point">Advice &amp; Guide. | Save your date. | Forever free.</h3>
							<%= image_tag("cycle-graphic.png", :alt => "Wedding couple just married", :class => "graphic img-responsive") %>
							<%= link_to "Get start today", '#', :class => "btn tp-btn-default tp-btn-lg" %>
					</div>
					<div class="col-md-12">
						<div class="col-md-12 aboutus">
							<h1>We want you to have a perfect wedding.</h1>
							<p class="lead">Welcome to Arusifiti An online Wedding Vendor Directory, launch in 2015. We pride our selves on being a trusted friend someone to take on this journey with you making it fun from the start.</p>
							<p>We will  support you and advise you. We are never short of suggestions or inspiring ideas.Our matchless, which makes finding beautiful wedding venue easier and one less thing for you to worry about.With our inspir blog, suggestions and sensational offers, no one understands weddings better than we do.</p>
						</div>
					</div>
					<div class="col-md-12 team-section" id="team">
						<h1>Our Founder and CEO</h1>
						<div class="row">

							<div class="col-md-3">				
								<%= image_tag("founder.jpg", :alt => "Founder-Image", :class => "img-responsive img-circle") %>		
							</div>
							
							<div class="col-md-8">
								<h2>Lawrence Chege</h2>
								<p>Nullam pellentesque congue ante ellentesque eget odio faucibus laoreet at pulvinar augueras ornare tincidunt nibh sodales tempus urabitur justo elit laoreet sed elit quis auctor placerat magna.</p>
								<p>Find him on Twitter <a href="#">@lawchege</a></p>
							</div>
						</div>
						<div class="row team-section">
							<div class="col-md-3 text-center team-block">
									<div class="team-pic">
										<!-- team pic --> 
										<%= link_to image_tag("team-pic1.jpg", alt: "", class: "img-responsive"),'#' %>	
									</div>
									<!-- /.team pic -->
									<h2><a href="#">Irene Wambui</a></h2>
									<span> Operations Officer</span>

									<div class="">
					                	<%= link_to ("#") do %> <i class='fa fa-twitter-square'> </i> <% end %>
					                 	<%= link_to ("#") do %> <i class='fa fa-linkedin-square'> </i> <% end %>
                					</div>

									</div>
									<div class="col-md-3 text-center team-block">
											<div class="team-pic">
												<!-- team pic --> 
												<%= link_to image_tag("team-pic7.jpg", alt: "", class: "img-responsive"),'#' %>
											</div>
											<!-- /.team pic -->
											<h2><a href="#">Marie Natasha</a></h2>
											<span>Operations Officer</span>

											<div class="">
							                	<%= link_to ("#") do %> <i class='fa fa-twitter-square'> </i> <% end %>
							                 	<%= link_to ("#") do %> <i class='fa fa-linkedin-square'> </i> <% end %>
		                					</div>

											</div>
											<div class="col-md-3 text-center team-block">
													<div class="team-pic">
														<!-- team pic --> 
														<%= link_to image_tag("team-pic8.jpg", alt: "", class: "img-responsive"),'#' %>	
													</div>
													<!-- /.team pic -->
													<h2><a href="#">Avery Goodly</a></h2>
													<span>Technical Officer</span>

													<div class="">
									                	<%= link_to ("#") do %> <i class='fa fa-twitter-square'> </i> <% end %>
									                 	<%= link_to ("#") do %> <i class='fa fa-linkedin-square'> </i> <% end %>
				                					</div>

													</div>
													<div class="col-md-3 text-center team-block">
															<div class="team-pic">
																<!-- team pic --> 
																<%= link_to image_tag("team-pic2.jpg", alt: "", class: "img-responsive"),'#' %> 
															</div>
															<!-- /.team pic -->
															<h2><a href="#">Jimmie Changa</a></h2>
															<span>Sales Executive </span>

															<div class="">
											                	<%= link_to ("#") do %> <i class='fa fa-twitter-square'> </i> <% end %>
											                 	<%= link_to ("#") do %> <i class='fa fa-linkedin-square'> </i> <% end %>
						                					</div>

															</div>

														</div>
													</div>
												</div>
												<div class="row">
													<div class="col-md-12 how-it-works" id="howwork">
														<h1>How It Works</h1>
														<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac purus eleifend, eleifend risus feugiat, consectetur extiam fermentum ligula ipsumincipsum dolor sit quis nisi dolor. </p>
														<div class="row">
															<div class="col-md-6 how-it-desc">
																<h2>Find the Vender</h2>
																<p>Sed id mollis exnteger eu veeger eu vehicula exliquam ultrices quis sem sed rutrumpendisse potentt laoreet faucibusus.</p>
															</div>
															<div class="col-md-4 text-center how-it-icon-vendor-find"> </div>
														</div>
														<div class="row">
															<div class="col-md-4 text-center how-it-icon-list"> </div>
															<div class="col-md-6 how-it-desc">
																<h2>Compare Proposal</h2>
																<p>Integer eu vehicula ex. Aliquam ultrices quis sem sed rutrum. Suspendisse potenti. Nam commodo nisi ut laoreet faucibus.</p>
															</div>
														</div>
														<div class="row">
															<div class="col-md-6 how-it-desc">
																<h2>Hire the Right Vender</h2>
																<p>Aliquam ultrices quis sem sed rutrumpendisse potenti. Nam commodo nisi ut laoreet faucibus lacus neque mollis nequeue libero at quam. </p>
															</div>
															<div class="col-md-4 text-center how-it-icon-vendor-done"> </div>
														</div>
													</div>
												</div>
												<div class="row">
													<div class="col-md-12 history" id="history">
														<h1>History</h1>
														<p>Cras acmetus sed arcu posuere interdu murabitur nunc sapienravida nec tempus eumn fermentum vitae erat raesent hendrerit ligula urnaonsec teturipsum estibulum justo ligula.</p>
													</div>
													<div class="col-md-12">
														<ul class="timeline">
															<li>
																<div class="tl-circ"></div>
																<div class="timeline-panel">
																	<div class="history-pic"> 
																		
																		<%= image_tag("post-pic.jpg", :alt => "", :class => "img-responsive") %> </div>
																	
																	<div class="tl-heading">
																		<h1>2008</h1>
																	</div>
																	<div class="tl-body">
																		<h3>The Wedding Vandor Begins</h3>
																		<p>Nullam ultricies venenatis enim sed sagittis. Donec sodales, eros necerisque suscipitonec
																			vitae elit dictum lectus gravida malesuadaInteger sapien nibh, bibendum a arcu quis.</p>
																		</div>
																	</div>
																</li>
																<li class="timeline-inverted">
																	<div class="tl-circ"></div>
																	<div class="timeline-panel">
																		<div class="history-pic"> 
																		
																			<%= image_tag("post-pic.jpg", :alt => "", :class => "img-responsive") %> </div>
																		
																		<div class="tl-heading">
																			<h1>2012</h1>
																		</div>
																		<div class="tl-body">
																			<h3>The First Office</h3>
																			<p>Nullam ultricies venenatis enim sed sagittis. Donec sodales, eros necerisque suscipitonec
																				vitae elit dictum lectus gravida malesuadaInteger sapien nibh, bibendum a arcu quis.</p>
																			</div>
																		</div>
																	</li>
																	<li>
																		<div class="tl-circ"></div>
																		<div class="timeline-panel">
																			<div class="history-pic"> 
																		
																			<%= image_tag("post-pic.jpg", :alt => "", :class => "img-responsive") %> </div>

																			<div class="tl-heading">
																				<h1>2014</h1>
																			</div>
																			<div class="tl-body">
																				<h3>Expansion </h3>
																				<p>Nullam ultricies venenatis enim sed sagittis. Donec sodales, eros necerisque suscipitonec
																					vitae elit dictum lectus gravida malesuadaInteger sapien nibh, bibendum a arcu quis.</p>
																				</div>
																			</div>
																		</li>
																		<li class="timeline-inverted">
																			<div class="tl-circ"></div>
																			<div class="timeline-panel">
																				<div class="history-pic"> 
																		
																				<%= image_tag("post-pic.jpg", :alt => " ", :class => "img-responsive") %> </div>

																				<div class="tl-heading">
																					<h1>2015</h1>
																				</div>
																				<div class="tl-body">
																					<h3>Today Wedding Vandor </h3>
																					<p>Nullam ultricies venenatis enim sed sagittis. Donec sodales, eros necerisque suscipitonec
																						vitae elit dictum lectus gravida malesuadaInteger sapien nibh, bibendum a arcu quis.</p>
																					</div>
																				</div>
																			</li>
																		</ul>
																	</div>
																</div>
															</div>
														</div>
													</div>
												</div>

app/views/welcome/contact.html.erb
<%provide(:title, "Contact") %>

app/views/welcome/index.html.erb
<div class="slider-bg">

	<!-- slider start-->
  <div class="hero-item" >
		<div><%= image_tag("arusi-img-1.jpg", alt: "Wedding couple just married") %> </div>    	
	</div>
  <!-- slider start-->
  
	<div class="find-section"><!-- Find search section-->
      <div class="container">
        <div class="row">
          <div class="col-md-offset-1 col-md-8 finder-block">
            <div class="finder-caption">
              <h1>Find your perfect Wedding Vendor</h1>
              <p>Over <strong>1200+ Wedding Vendor </strong>for you special date &amp; Find the perfect venue &amp; save you date.</p>
            </div>

            <div class="finderform">
            <%= form_tag ('/search') do %>
                
                <div class="form-group col-md-9 no-padding">
                	
                <%= text_field_tag 'search', nil, class: 'form-control', placeholder: 'What are you looking for...' %>

                </div>               
                <button type="submit" class="btn tp-btn-default tp-btn-lg">Find Vendors</button>
             <% end %>

            </div>
          </div>
        </div>
      </div>
    </div>

  <!-- /.Find search section-->

</div>

<!-- slider end-->

 <div class="spacer feature-section"><!-- Feature Blog Start -->
    <div class="container">
      <div class="row">
        <div class="col-md-12 tp-title-center">
          <h1>Your Wedding Planing Start Here</h1>
        </div>
      </div>
      <div class="row feature-center"><!-- feature center -->
        <div class="col-md-4 feature-block"><!-- feature block -->
          <div class="feature-icon-vendor"></div>
          <h2>Find local vendor</h2>
          <p>Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text.</p>
        </div><!-- /.feature block -->
        <div class="col-md-4 feature-block"><!-- feature block -->
          <div class="feature-icon-mail"></div>
          <h2>Contact vendor</h2>
          <p>Various versions have evolved over the years, sometimes by accident, sometimes on purpose 
            (injected humour and the like).</p>
        </div><!-- /.feature block -->
        <div class="col-md-4 feature-block"><!-- feature block -->
          <div class="feature-icon-couple"></div>
          <h2>Save Your Date</h2>
          <p>The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.</p>
        </div><!-- /.feature block -->
      </div><!-- /.feature center -->
    </div>
  </div>
  <!-- Feature Blog End -->

  <div class="tp-section spacer">
    <div class="container">
      <div class="row">
        <div class="col-md-12 tp-title-center">
          <h1>Featured Wedding Vendor</h1>
        </div>
      </div>
      <div class="row ">
        <div class="col-md-4 vendor-box"><!-- venue box start-->
          <div class="vendor-image"><!-- venue pic --> 
          	<%= link_to image_tag("vendor-1.jpg", alt: "wedding venue", class: "img-responsive"),'#' %>	
            <div class="feature-label"></div>
            <div class="favourite-bg"><a href="#" class=""><i class="fa fa-heart"></i></a></div>
          </div>
          <!-- /.venue pic -->
          <div class="vendor-detail"><!-- venue details -->
            <div class="caption"><!-- caption -->
              <h2><a href="#" class="title">Venue Vendor Title</a></h2>
              <p class="location"><i class="fa fa-map-marker"></i> Street Address, Name of Town, 12345, Country.</p>
              <div class="rating"> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star-o"></i> <span class="rating-count">(22)</span> </div>
            </div>
            <!-- /.caption -->
            <div class="vendor-price">
              <div class="price">$390 - $600</div>
            </div>
          </div>
          <!-- venue details --> 
        </div>
        
        <!-- /.venue box start-->
        <div class="col-md-4 vendor-box"><!-- venue box start-->
          <div class="vendor-image"><!-- venue pic --> 
          	<%= link_to image_tag("vendor-4.jpg", alt: "wedding venue", class: "img-responsive"),'#' %>	
            <div class="rated-label"></div>
            <div class="favourite-bg"><a href="#" class=""><i class="fa fa-heart"></i></a></div>
          </div>
          <!-- /.venue pic -->
          <div class="vendor-detail"><!-- venue details -->
            <div class="caption"><!-- caption -->
              <h2><a href="#" class="title"> Wedding Dress Vendor Title</a></h2>
              <p class="location"><i class="fa fa-map-marker"></i> Street Address, Name of Town, 12345, Country.</p>
              <div class="rating"> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star-o"></i> <span class="rating-count">(22)</span> </div>
            </div>
            <!-- /.caption -->
            <div class="vendor-price">
              <div class="price">$390 - $600</div>
            </div>
          </div>
          <!-- venue details --> 
        </div>
        <!-- /.venue box start-->
        <div class="col-md-4 vendor-box"><!-- venue box start-->
          <div class="vendor-image"><!-- venue pic --> 
          	<%= link_to image_tag("vendor-3.jpg", alt: "wedding venue", class: "img-responsive"),'#' %>	
            <div class="popular-label"></div>
            <div class="favourite-bg"><a href="#" class=""><i class="fa fa-heart"></i></a></div>
          </div>
          <!-- /.venue pic -->
          <div class="vendor-detail"><!-- venue details -->
            <div class="caption"><!-- caption -->
              <h2><a href="#" class="title">Vendor Photographer Title</a></h2>
              <p class="location"><i class="fa fa-map-marker"></i> Street Address, Name of Town, 12345, Country.</p>
              <div class="rating"> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star-o"></i> <span class="rating-count">(22)</span> </div>
            </div>
            <!-- /.caption -->
            <div class="vendor-price">
              <div class="price">$390 - $600</div>
            </div>
          </div>
          <!-- venue details --> 
        </div>
      </div>
    </div>
  </div>